# Implementing Tutorial in python using the iris dataset
## DISCRIMINANT ANALYSIS IN THE GAUSSIAN FRAMEWORK
### Problem Statement and Hypothesis
In the very first place, our goal is: from the following dataset, $$ \left\{ (x_i,y_i \right\}_{i=1}^n ~where ~ (x_i,y_i)\in \mathbb{R}^p \times \{1,\ldots,k\} ~with~ k\in \mathbb{N} \backslash \{0,1\} ~and~\{1,\ldots,k\} ~not~ ordered$$  predict the class of an individual $X$ using the Bayes classifier
\begin{eqnarray}
        g^*(x) &=& \arg\max_{k\in\{1,\ldots,k\}} \frac{\mathbb{P}(Y=k)f_{X|Y=k}(x)}{\displaystyle{\sum_{h=1}^K \mathbb{P}(Y=h)f_{X|Y=h}(x)}} \\ &=&\arg\max_{k\in\{1,\ldots,k\}} \mathbb{P}(Y=k)f_{X|Y=k}(x)
\end{eqnarray}

$$where~f_{X|Y=k}(x):= \mathscr{N}(x; \mu_k, \Lambda_k) = \frac{1}{(2\pi)^{\frac{p}{2}} \left| \Lambda_k \right|^{\frac{1}{2}}} \exp\left[ -\frac{1}{2} ~ ^t (x-\mu_k)\Lambda_k^{-1}(x-\mu_k) \right]$$

But, we realise that this classifier, depends on variables which we don't know $$\theta = \left( (\omega_k)_{k=1}^K,  (\mu_k)_{k=1}^K,  (\Lambda_k)_{k=1}^K\right)$$ after getting the boundary equation between two classes $(k$ and $k')$ for $k>2$, given as:
$$ \frac{1}{2} \ln \frac{|\Lambda_{k'}|}{|\Lambda_k|} + \ln\frac{\omega_k}{\omega_{k'}} + \frac{1}{2} \left[ ^t (x-\mu_{k'})\Lambda_{k'}^{-1}(x-\mu_{k'}) - ^t (x-\mu_k)\Lambda_k^{-1}(x-\mu_k) \right] = 0$$ Where $\omega_k = \mathbb{P}(Y=k)$

#### Estimating $\theta$
$\mathbb{P}(Y_i = k) = \omega_k$$~;~~$   $f_{X|Y=k}(x):= \mathscr{N}(x; \mu_k, \Lambda_k)$, we record the $Y_i$'s in $Z_i = \left( Z_{i,k} \right)_{k=1}^K \in \left\{ 0,1 \right\}$ where $Z_{i,k} = \mathbb{P}(Z_{i,k}=1) = \omega_k$. The dataset now becomes 
$$\mathscr{A}_n = \left\{ (x_i,y_i) \right\}_{i=1}^n = \left\{ \left( x_i; (z_{i,k})_{k=1}^K \right) \right\}  $$

Our goal now boils down to estimating these variables since we do not know them and to do this, we estimate them by calculating the maximum likelihood estimator $$\widehat{\theta} = \left( (\widehat{\omega}_k)_{k=1}^K,  (\widehat{\mu}_k)_{k=1}^K,  (\widehat{\Lambda}_k)_{k=1}^K\right) \in \arg\max_{\theta} L\left( \theta,(x,y) \right)$$ where 
$$ L\left( \theta,(x,y) \right) = \sum_{i=1}^n \sum_{k=1}^K z_{i,k} \left[ \ln\left( \frac{1}{(2\pi)^{\frac{p}{2}} \left| \Lambda_k \right|^{\frac{1}{2}}} \right) - \frac{1}{2} ~ ^t (x_i-\mu_k)\Lambda_k^{-1}(x_i-\mu_k) + \ln{\omega_k}\right] + \lambda \left( \sum_{k=1}^K \omega_k - 1\right)$$
$$and,~~ \left\{ \begin{array}{l}
    n_k = \displaystyle{\sum_{i=1}^nz_{i,k}} \\
    \widehat{\omega} = \displaystyle{\frac{n_k}{n}} \\
    \widehat{\mu}_k = \displaystyle{\frac{1}{n_k} \sum_{i=1}^nz_{i,k}x_i} \\
    \displaystyle{\widehat{\Lambda}_k =  \frac{1}{n_k} \sum_{i=1}^nz_{i,k} (x_i-\widehat{\mu}_k) ~^t (x_i-\widehat{\mu}_k)}
 \end{array} \right.
 $$
 After all the calculations done on L using Langrangien optimisation based on variables, we obtain the expressions for $n_k, \widehat{\omega},\widehat{\mu}_k and \widehat{\Lambda}_k $ as seen above. We also come out with the following discriminant function for the class $k$
 $$\widehat{\delta}_k(x) = -\frac{1}{2} \ln \left|\widehat{\Lambda}_k\right| + \ln \widehat{\omega}_k - \frac{1}{2} ~ ^t (x-\widehat{\mu}_k)\Lambda_k^{-1}(x-\widehat{\mu}_k)$$

 Finally, we have estimated $\theta$ on which our predictor depends, we therefore can determine our classifier using 
$$\widehat{g}(x) = \arg\max_k\widehat{\delta}_k(x) $$
 
 In second place we are going to use $\Lambda$ calculated as follows  
 $$\widehat{\Lambda} =  \frac{1}{n} \sum_{i=1}^n \sum_{k=1}^Kz_{i,k} (x_i-\widehat{\mu}_k) ~^t (x_i-\widehat{\mu}_k)$$
 and it's corresponding $\widehat{\delta}_k(x)$ as follows
 $$\widehat{\delta}_k(x) = -\frac{1}{2} \ln \left|\widehat{\Lambda}\right| + \ln \widehat{\omega}_k - \frac{1}{2} ~ ^t (x-\widehat{\mu}_k)\Lambda^{-1}(x-\widehat{\mu}_k)$$


In [1]:
#importing of various libraries
import numpy as np
import sklearn as skl
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import datasets

###  Iris Dataset

In [2]:
#loading the iris dataset
iris = datasets.load_iris()
iris_X = iris.data
iris_Y = iris.target


### Calculating Z


In [3]:
k = 2
Z = []
for i in range(len(iris_Y)):
    Z.append([None]*(k+1))
    for j in range(k+1):
        if(iris_Y[i] == j):
            Z[i][j] = 1
        else:
            Z[i][j] = 0

### Estimation of $\theta$ using a class MyEstimator

In [4]:
#Estimation of \theta
class MyEstimator(object):
    def __init__(self,Z,X,n,k):
        self._X = X.copy()
        self._Z = Z.copy()
        self._n = n
        self._k = k
        
    # maximum likelihood estimator of nk    
    def Nk(self):
        nk = []
        for j in range (k+1):
            nk.append(0) 
            for i in range(self._n):
                nk[j] += self._Z[i][j]
        return nk
    
     # maximum likelihood estimator of wk 
    def Wk(self):
        self._nk = self.Nk()
        wk = []
        for j in range(len(self._nk)):
            wk.append(0)
            wk[j] = self._nk[j]/self._n
        return wk
    
     # maximum likelihood estimator of Muk 
    def Muk(self):
        Muk = []
        self._nk = self.Nk()
        for j in range (k+1):
            #Muk.append([0,0,0,0])
            Muk.append([0]*len(self._X[0])) 
            for i in range(self._n):
                Muk[j] += (1/self._nk[j])*(self._Z[i][j]*np.matrix(self._X[i]))
        return Muk
    
    def transP(self,a):
        b = np.array([a])
        return b.T
    
    #maximum likelihood estimator of Lamdak
    def Lamdak(self):
        Lamdak = []
        self._Muk = self.Muk()
        for j in range (k+1):
            Lamdak.append([0]*len(self._X[0])) 
            for i in range(self._n):
                D = self._X[i] - self._Muk[j]
                # TODO Ask teacher about I have a problem with the method below
                Lamdak[j] += (1/self._nk[j])*(self._Z[i][j]*np.matrix(D).T.dot(np.matrix(D)))
        return Lamdak
    
    #maximum likelihood estimator of Lamda
    def Lamda(self):
        Lamda = []
        prod = []
        Lamda.append([0]*len(self._X[0]))
        self._Muk = self.Muk()
        for i in range(self._n):
            for j in range (k+1):
                prod.append([0]*len(self._X[0]))
                D = self._X[i] - self._Muk[j]
                prod[i] += (self._Z[i][j]*np.matrix(D).T.dot(np.matrix(D)))
            Lamda += (1/self._n)*prod[i]
        return Lamda
    
    #Discriminant function of every class k for a given X using Lamdak
    def sigmaCap(self,X):
        sigmacap = []
        self._lamdak = self.Lamdak()
        self._wk = self.Wk()
        for j in range (k+1):
            sigmacap.append(0) 
            D = X - self._Muk[j]
            # TODO Ask teacher about I have a problem with the method below
            sigmacap[j] = -0.5*np.log(np.linalg.det(self._lamdak[j])) + np.log(self._wk[j]) - 0.5*np.matrix(D).dot(np.linalg.inv(self._lamdak[k])).dot(np.matrix(D).T) 
        return sigmacap
    
     #Discriminant function of every class k for a given X using Lamda 
    def sigmaCapLamda(self,X):
        sigmacapLamda = []
        self._lamda = self.Lamda()
        self._wk = self.Wk()
        for j in range (k+1):
            sigmacapLamda.append(0) 
            D = X - self._Muk[j]
            sigmacapLamda[j] = -0.5*np.log(np.linalg.det(self._lamda)) + np.log(self._wk[j]) - 0.5*np.matrix(D).dot(np.linalg.inv(self._lamda)).dot(np.matrix(D).T) 
        return sigmacapLamda
    
     #Determining the class of a given X 
        '''
            This method is used to predict using Lamdak
        '''
    def gcap(self,X):
        gcap = self.sigmaCap(X)
        index = gcap.index(np.max(gcap))
        return index
    
     #Determining the class of a given X using Lamda
        '''
            This method is used to predict using Lamda
        '''
    def gcapLamda(self,X):
        gcap = self.sigmaCapLamda(X)
        index = gcap.index(np.max(gcap))
        return index

#### Calculating Using $\widehat{\Lambda}_k$

In [5]:
est = MyEstimator(Z,iris_X,len(iris_Y),2)

##### Estimating $n_k$

In [6]:
est.Nk()

[50, 50, 50]

##### Estimating $\widehat{\omega}_k$

In [7]:
est.Wk()

[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]

##### Estimating $\widehat{\mu}_k$

In [8]:
est.Muk()

[matrix([[5.006, 3.418, 1.464, 0.244]]),
 matrix([[5.936, 2.77 , 4.26 , 1.326]]),
 matrix([[6.588, 2.974, 5.552, 2.026]])]

##### Estimating $\widehat{\Lambda}_k$

In [9]:
est.Lamdak()

[matrix([[0.121764, 0.098292, 0.015816, 0.010336],
         [0.098292, 0.142276, 0.011448, 0.011208],
         [0.015816, 0.011448, 0.029504, 0.005584],
         [0.010336, 0.011208, 0.005584, 0.011264]]),
 matrix([[0.261104, 0.08348 , 0.17924 , 0.054664],
         [0.08348 , 0.0965  , 0.081   , 0.04038 ],
         [0.17924 , 0.081   , 0.2164  , 0.07164 ],
         [0.054664, 0.04038 , 0.07164 , 0.038324]]),
 matrix([[0.396256, 0.091888, 0.297224, 0.048112],
         [0.091888, 0.101924, 0.069952, 0.046676],
         [0.297224, 0.069952, 0.298496, 0.047848],
         [0.048112, 0.046676, 0.047848, 0.073924]])]

##### Implementing class on iris.data

In [10]:
es = []
nb = 0
for i in range(len(iris_Y)):
    es.append(est.gcap(iris_X[i]))
    if(es[i] != iris_Y[i]):
        nb += 1
        print("For {}, {} ({}) predicted instead of {} ({}).".format(iris_X[i],es[i],iris.target_names[es[i]],iris_Y[i],iris.target_names[iris_Y[i]]))
    else:
        print("For {}, {} ({}) predicted as expected.".format(iris_X[i],es[i],iris.target_names[es[i]]))
print("\nSorry I failed {} times".format(nb))

For [5.1 3.5 1.4 0.2], 0 (setosa) predicted as expected.
For [4.9 3.  1.4 0.2], 0 (setosa) predicted as expected.
For [4.7 3.2 1.3 0.2], 0 (setosa) predicted as expected.
For [4.6 3.1 1.5 0.2], 0 (setosa) predicted as expected.
For [5.  3.6 1.4 0.2], 0 (setosa) predicted as expected.
For [5.4 3.9 1.7 0.4], 0 (setosa) predicted as expected.
For [4.6 3.4 1.4 0.3], 0 (setosa) predicted as expected.
For [5.  3.4 1.5 0.2], 0 (setosa) predicted as expected.
For [4.4 2.9 1.4 0.2], 0 (setosa) predicted as expected.
For [4.9 3.1 1.5 0.1], 0 (setosa) predicted as expected.
For [5.4 3.7 1.5 0.2], 0 (setosa) predicted as expected.
For [4.8 3.4 1.6 0.2], 0 (setosa) predicted as expected.
For [4.8 3.  1.4 0.1], 0 (setosa) predicted as expected.
For [4.3 3.  1.1 0.1], 0 (setosa) predicted as expected.
For [5.8 4.  1.2 0.2], 0 (setosa) predicted as expected.
For [5.7 4.4 1.5 0.4], 0 (setosa) predicted as expected.
For [5.4 3.9 1.3 0.4], 0 (setosa) predicted as expected.
For [5.1 3.5 1.4 0.3], 0 (setos

For [6.  3.  4.8 1.8], 2 (virginica) predicted as expected.
For [6.9 3.1 5.4 2.1], 2 (virginica) predicted as expected.
For [6.7 3.1 5.6 2.4], 2 (virginica) predicted as expected.
For [6.9 3.1 5.1 2.3], 2 (virginica) predicted as expected.
For [5.8 2.7 5.1 1.9], 2 (virginica) predicted as expected.
For [6.8 3.2 5.9 2.3], 2 (virginica) predicted as expected.
For [6.7 3.3 5.7 2.5], 2 (virginica) predicted as expected.
For [6.7 3.  5.2 2.3], 2 (virginica) predicted as expected.
For [6.3 2.5 5.  1.9], 2 (virginica) predicted as expected.
For [6.5 3.  5.2 2. ], 2 (virginica) predicted as expected.
For [6.2 3.4 5.4 2.3], 2 (virginica) predicted as expected.
For [5.9 3.  5.1 1.8], 2 (virginica) predicted as expected.

Sorry I failed 4 times


##### Probable risk

In [11]:
print("Risk = {} %".format(nb/len(iris_Y)*100))

Risk = 2.666666666666667 %


#### Calculating using $\Lambda$

 ##### $\widehat{\omega}_k$ and  $\widehat{\mu}_k$ remain thesame as above

##### Estimating $\widehat{\Lambda}$

In [12]:
est.Lamda() 

matrix([[0.259708  , 0.09122   , 0.16409333, 0.037704  ],
        [0.09122   , 0.11356667, 0.05413333, 0.03275467],
        [0.16409333, 0.05413333, 0.18146667, 0.04169067],
        [0.037704  , 0.03275467, 0.04169067, 0.04117067]])

##### Implementing on iris.data

In [13]:
es = []
nb = 0
for i in range(len(iris_Y)):
    es.append(est.gcapLamda(iris_X[i]))
    if(es[i] != iris_Y[i]):
        nb += 1
        print("For {}, {} ({}) predicted instead of {} ({}).".format(iris_X[i],es[i],iris.target_names[es[i]],iris_Y[i],iris.target_names[iris_Y[i]]))
    else:
        print("For {}, {} ({}) predicted as expected.".format(iris_X[i],es[i],iris.target_names[es[i]]))
print("\nSorry I failed {} times".format(nb))

For [5.1 3.5 1.4 0.2], 0 (setosa) predicted as expected.
For [4.9 3.  1.4 0.2], 0 (setosa) predicted as expected.
For [4.7 3.2 1.3 0.2], 0 (setosa) predicted as expected.
For [4.6 3.1 1.5 0.2], 0 (setosa) predicted as expected.
For [5.  3.6 1.4 0.2], 0 (setosa) predicted as expected.
For [5.4 3.9 1.7 0.4], 0 (setosa) predicted as expected.
For [4.6 3.4 1.4 0.3], 0 (setosa) predicted as expected.
For [5.  3.4 1.5 0.2], 0 (setosa) predicted as expected.
For [4.4 2.9 1.4 0.2], 0 (setosa) predicted as expected.
For [4.9 3.1 1.5 0.1], 0 (setosa) predicted as expected.
For [5.4 3.7 1.5 0.2], 0 (setosa) predicted as expected.
For [4.8 3.4 1.6 0.2], 0 (setosa) predicted as expected.
For [4.8 3.  1.4 0.1], 0 (setosa) predicted as expected.
For [4.3 3.  1.1 0.1], 0 (setosa) predicted as expected.
For [5.8 4.  1.2 0.2], 0 (setosa) predicted as expected.
For [5.7 4.4 1.5 0.4], 0 (setosa) predicted as expected.
For [5.4 3.9 1.3 0.4], 0 (setosa) predicted as expected.
For [5.1 3.5 1.4 0.3], 0 (setos

For [6.7 3.1 5.6 2.4], 2 (virginica) predicted as expected.
For [6.9 3.1 5.1 2.3], 2 (virginica) predicted as expected.
For [5.8 2.7 5.1 1.9], 2 (virginica) predicted as expected.
For [6.8 3.2 5.9 2.3], 2 (virginica) predicted as expected.
For [6.7 3.3 5.7 2.5], 2 (virginica) predicted as expected.
For [6.7 3.  5.2 2.3], 2 (virginica) predicted as expected.
For [6.3 2.5 5.  1.9], 2 (virginica) predicted as expected.
For [6.5 3.  5.2 2. ], 2 (virginica) predicted as expected.
For [6.2 3.4 5.4 2.3], 2 (virginica) predicted as expected.
For [5.9 3.  5.1 1.8], 2 (virginica) predicted as expected.

Sorry I failed 3 times


##### Probable risk

In [14]:
print("Risk = {} %".format(nb/len(iris_Y)*100))

Risk = 2.0 %
